// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using application.Data;

#nullable disable

namespace application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619155807_add coworking entity")]
    partial class addcoworkingentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityWorkspaceType", b =>
                {
                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("AmenityId", "WorkspaceTypeId");

                    b.HasIndex("WorkspaceTypeId");

                    b.ToTable("AmenityWorkspaceType");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            AmenityId = 2,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            AmenityId = 3,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            AmenityId = 1,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            AmenityId = 3,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            AmenityId = 4,
                            WorkspaceTypeId = 2
                        });
                });

            modelBuilder.Entity("application.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "High-Speed Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Power Outlets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Coffee Machine"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Air Conditioning"
                        });
                });

            modelBuilder.Entity("application.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("application.Models.Coworking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coworkings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Yaroslav Val St,Kyiv",
                            Name = "WorkClub Perchersk"
                        });
                });

            modelBuilder.Entity("application.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkspaceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceTypeId");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            Name = "Desk 1",
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            Name = "Desk 2",
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1,
                            Name = "Desk 3",
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            Name = "Desk 4",
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 1,
                            Name = "Desk 5",
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 1,
                            Name = "Room 1",
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1,
                            Name = "Room 2",
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            Name = "Room 3",
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 5,
                            Name = "Room 4",
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10,
                            Name = "Room 5",
                            WorkspaceTypeId = 2
                        });
                });

            modelBuilder.Entity("application.Models.WorkspaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoworkingId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoworkingId");

                    b.ToTable("WorkspaceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoworkingId = 1,
                            Description = "A vibrant shared are perfect for freelancers or small teams who enjoy a collaborative atmosphere. Choose any available desk and get to work with flexibility and ease",
                            ImageUrl = "/images/open-space/openSpace.jpg",
                            Name = "Open Space"
                        },
                        new
                        {
                            Id = 2,
                            CoworkingId = 1,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed room offer privacy and come in a variety of sizes to fit your needs",
                            ImageUrl = "/images/private-room/privateRoom.jpg",
                            Name = "Private Room"
                        });
                });

            modelBuilder.Entity("AmenityWorkspaceType", b =>
                {
                    b.HasOne("application.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("application.Models.WorkspaceType", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("application.Models.Booking", b =>
                {
                    b.HasOne("application.Models.Workspace", "Workspace")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("application.Models.Workspace", b =>
                {
                    b.HasOne("application.Models.WorkspaceType", "WorkspaceType")
                        .WithMany("Workspaces")
                        .HasForeignKey("WorkspaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkspaceType");
                });

            modelBuilder.Entity("application.Models.WorkspaceType", b =>
                {
                    b.HasOne("application.Models.Coworking", "CoworkingSpace")
                        .WithMany("WorkspaceTypes")
                        .HasForeignKey("CoworkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoworkingSpace");
                });

            modelBuilder.Entity("application.Models.Coworking", b =>
                {
                    b.Navigation("WorkspaceTypes");
                });

            modelBuilder.Entity("application.Models.Workspace", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("application.Models.WorkspaceType", b =>
                {
                    b.Navigation("Workspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
