// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using application.Data;

#nullable disable

namespace application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619193307_add additional seeded data and remove name from workspace")]
    partial class addadditionalseededdataandremovenamefromworkspace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmenityWorkspaceType", b =>
                {
                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("AmenityId", "WorkspaceTypeId");

                    b.HasIndex("WorkspaceTypeId");

                    b.ToTable("AmenityWorkspaceType");

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            AmenityId = 2,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            AmenityId = 3,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            AmenityId = 1,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            AmenityId = 3,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            AmenityId = 4,
                            WorkspaceTypeId = 2
                        });
                });

            modelBuilder.Entity("application.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "High-Speed Wi-Fi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Power Outlets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Coffee Machine"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Air Conditioning"
                        });
                });

            modelBuilder.Entity("application.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("application.Models.Coworking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Coworkings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Yaroslav Val St, Kyiv",
                            Description = "Modern coworking in the heart of Pechersk with quiet rooms and coffee on tap",
                            ImageUrl = "https://www.mindspace.me/wp-content/uploads/2023/08/Screenshot-2023-08-17-at-08.57.35.png",
                            Name = "WorkClub Perchersk"
                        },
                        new
                        {
                            Id = 2,
                            Address = "78 Naberezhno-Khreshachatytska ST, Kyiv",
                            Description = "A creative riverside hub ideal for freelancers and small startups",
                            ImageUrl = "https://mlgucbjxeu1m.i.optimole.com/cb:B7VA.3e989/w:1024/h:682/q:mauto/ig:avif/f:best/https://flydesk.com/wp-content/uploads/2021/01/lavaca-barcelona-coworking.jpg",
                            Name = "UrbanSpace Podil"
                        },
                        new
                        {
                            Id = 3,
                            Address = "12 Lvivska Square,Kyiv",
                            Description = "A compact, desight-focused space with open desks and strong community vibes",
                            ImageUrl = "https://www.servcorp.com.au/media/31088/socialising-in-a-coworking-space.jpg",
                            Name = "Creative Hub Lvivska"
                        });
                });

            modelBuilder.Entity("application.Models.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("WorkspaceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceTypeId");

                    b.ToTable("Workspaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 1,
                            WorkspaceTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 1,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 1,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 2,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 5,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10,
                            WorkspaceTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 1,
                            WorkspaceTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 1,
                            WorkspaceTypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 1,
                            WorkspaceTypeId = 4
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 1,
                            WorkspaceTypeId = 4
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 1,
                            WorkspaceTypeId = 4
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 1,
                            WorkspaceTypeId = 5
                        },
                        new
                        {
                            Id = 17,
                            Capacity = 2,
                            WorkspaceTypeId = 5
                        },
                        new
                        {
                            Id = 18,
                            Capacity = 2,
                            WorkspaceTypeId = 5
                        },
                        new
                        {
                            Id = 19,
                            Capacity = 5,
                            WorkspaceTypeId = 5
                        },
                        new
                        {
                            Id = 20,
                            Capacity = 5,
                            WorkspaceTypeId = 5
                        },
                        new
                        {
                            Id = 21,
                            Capacity = 10,
                            WorkspaceTypeId = 6
                        },
                        new
                        {
                            Id = 22,
                            Capacity = 20,
                            WorkspaceTypeId = 6
                        });
                });

            modelBuilder.Entity("application.Models.WorkspaceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoworkingId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoworkingId");

                    b.ToTable("WorkspaceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoworkingId = 1,
                            Description = "A vibrant shared are perfect for freelancers or small teams who enjoy a collaborative atmosphere. Choose any available desk and get to work with flexibility and ease",
                            ImageUrl = "/images/open-space/openSpace.jpg",
                            Name = "Open Space"
                        },
                        new
                        {
                            Id = 2,
                            CoworkingId = 1,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed room offer privacy and come in a variety of sizes to fit your needs",
                            ImageUrl = "/images/private-room/privateRoom.jpg",
                            Name = "Private Room"
                        },
                        new
                        {
                            Id = 3,
                            CoworkingId = 1,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed room offer privacy and come in a variety of sizes to fit your needs",
                            ImageUrl = "https://www.appliedglobal.com/wp-content/uploads/How-to-Create-a-Modern-Meeting-Room-Setup.png",
                            Name = "Meeting Room"
                        },
                        new
                        {
                            Id = 4,
                            CoworkingId = 2,
                            Description = "A vibrant shared are perfect for freelancers or small teams who enjoy a collaborative atmosphere. Choose any available desk and get to work with flexibility and ease",
                            ImageUrl = "/images/open-space/openSpace.jpg",
                            Name = "Open Space"
                        },
                        new
                        {
                            Id = 5,
                            CoworkingId = 2,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed room offer privacy and come in a variety of sizes to fit your needs",
                            ImageUrl = "/images/private-room/privateRoom.jpg",
                            Name = "Private Room"
                        },
                        new
                        {
                            Id = 6,
                            CoworkingId = 2,
                            Description = "Ideal for focused work, video calls, or small team huddles. These fully enclosed room offer privacy and come in a variety of sizes to fit your needs",
                            ImageUrl = "https://www.appliedglobal.com/wp-content/uploads/How-to-Create-a-Modern-Meeting-Room-Setup.png",
                            Name = "Meeting Room"
                        });
                });

            modelBuilder.Entity("AmenityWorkspaceType", b =>
                {
                    b.HasOne("application.Models.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("application.Models.WorkspaceType", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("application.Models.Booking", b =>
                {
                    b.HasOne("application.Models.Workspace", "Workspace")
                        .WithMany("Bookings")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("application.Models.Workspace", b =>
                {
                    b.HasOne("application.Models.WorkspaceType", "WorkspaceType")
                        .WithMany("Workspaces")
                        .HasForeignKey("WorkspaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkspaceType");
                });

            modelBuilder.Entity("application.Models.WorkspaceType", b =>
                {
                    b.HasOne("application.Models.Coworking", "CoworkingSpace")
                        .WithMany("WorkspaceTypes")
                        .HasForeignKey("CoworkingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoworkingSpace");
                });

            modelBuilder.Entity("application.Models.Coworking", b =>
                {
                    b.Navigation("WorkspaceTypes");
                });

            modelBuilder.Entity("application.Models.Workspace", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("application.Models.WorkspaceType", b =>
                {
                    b.Navigation("Workspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
